import json
import os
import re
import torch
import yaml
from tqdm import tqdm
from typing import List, Tuple, Optional
from transformers import AutoTokenizer, AutoModel
from collections import defaultdict
from utils import llm_generation, mean_pooling, load_dataset

# Using a prompted LLM to break down research ideas into fine-grained viewpoints.
def viewpoint_extraction(idea: str, config: dict) -> Tuple[List[str], Optional[int]]:
    with open('Prompt/viewpoint_extraction_prompt.txt', 'r', encoding='utf-8') as file:
        sys_prompt = file.read()
    user_prompt = f"[The Start of Abstract]\n{idea}\n[The End of Abstract]"
    
    response, token_usage= llm_generation(sys_prompt, user_prompt, response_num=1, config=config)
    
    pattern = r"\[Extracted Viewpoints in Sentence \d+\]\n(.*?)(?=\n\[Sentence|$)"
    matches = re.findall(pattern, response, re.DOTALL)
    
    viewpoint_list = []
    for match in matches:
        viewpoints_list = re.findall(r"\[(.*?)\]", match)
        viewpoint_list.extend(viewpoints_list)
    return viewpoint_list, token_usage

# Constructing viewpoint-subgraphs using prompt-based LLM.
def prompt_based_edge_connection(idea: str, viewpoint_list: List[str], config: dict) -> Tuple[List[dict], Optional[int]]:
    with open('Prompt/graph_construction_prompt.txt', 'r', encoding='utf-8') as file:
        sys_prompt = file.read()
    user_prompt = f"[The Start of Abstract]\n{idea}\n[The End of Abstract]\n[The Start of Extracted Viewpoints]\n"
    for viewpoint in viewpoint_list:
        user_prompt += f"[{viewpoint}]\n"
    user_prompt += "[The End of Extracted Viewpoints]"
    
    response, token_usage = llm_generation(sys_prompt, user_prompt, response_num=1, config=config)
    
    pattern = re.compile(r"\{\[(.*?)\], \[(.*?)\], \[(supporting|opposing)\], \[(.*?)\]\}")
    matches = pattern.findall(response)
    
    viewpoint_pairs = []
    for match in matches:
        data = {
                "viewpoint1": match[0],
                "viewpoint2": match[3],
                "relation": match[2],
                "logical_connector": match[1],
                "weight": 0.0,
            }
        viewpoint_pairs.append(data)
    
    return viewpoint_pairs, token_usage

# This function takes the storage path of the research ideas dataset and the storage path of the extracted viewpoints as input 
# and outputs (stores) the edge list of the viewpoint-subgraphs generated by the prompted LLM.
# After setting up the config.yaml file, run the following command:
# python -c "from Graph_Extraction import prompt_based_subgraph_construction; prompt_based_subgraph_construction()"
def prompt_based_subgraph_construction():
    with open("config.yaml", 'r', encoding='utf-8') as file:
        config = yaml.safe_load(file)
    
    paper_dict = {}
    with open(config["dataset_path"], "r", encoding="utf-8") as f1:
        for line in f1:
            entry = json.loads(line.strip())
            paper_dict[entry["paper_id"]] = entry["abstract"]

    viewpoints_dict = defaultdict(list)
    viewpoint_to_node_id = {}
    
    for nodelist_path in config["node_list_paths"]:
        with open(nodelist_path, "r", encoding="utf-8") as f2:
            for line in f2:
                entry = json.loads(line.strip())
                node_id = entry["node_id"]
                viewpoint = entry["viewpoint"]
                
                prefix = node_id.split("[")[0]
                viewpoints_dict[prefix].append(viewpoint)
                viewpoint_to_node_id[viewpoint] = node_id

    temp = []
    for prefix, viewpoints_list in viewpoints_dict.items():
        if prefix in paper_dict:
            idea = paper_dict[prefix]
            temp.append((idea, viewpoints_list))

    edge_list = []
    for pair in temp:
        idea = pair[0]
        viewpoint_list = pair[1]
        viewpoint_pairs, token_usage = prompt_based_edge_connection(idea, viewpoint_list, config)
            
        for vp1, vp2, relation, logical_connector in viewpoint_pairs:
            node_id1 = viewpoint_to_node_id.get(vp1)
            node_id2 = viewpoint_to_node_id.get(vp2)
            if node_id1 and node_id2:
                data = {
                    "node_id1": node_id1,
                    "node_id2": node_id2,
                    "relation": relation,
                    "logical_connector": logical_connector,
                    "weight": 1.0,
                }
                edge_list.append(data)
    
    # Write edge list to file
    save = config["save_edge_list"]
    save_path = config["edge_list_save_path"]
    save_path = os.path.join(save_path, 'llm_based_edge_list.jsonl')
    if save:
        with open(save_path, 'w', encoding='utf-8') as f:
            for edge in edge_list:
                f.write(json.dumps(edge) + '\n')
    return edge_list          
    
# Using a bert-based model to obtain viewpoint node embeddings.    
def get_node_embedding(viewpoint_list: List[str], tokenizer: AutoTokenizer, encoder: AutoModel) -> List[torch.Tensor]:
    inputs = tokenizer(viewpoint_list, padding=True, truncation=True, return_tensors='pt')
    # Compute token embeddings
    outputs = encoder(**inputs)
    # Mean pooling
    embeddings = mean_pooling(outputs[0], inputs['attention_mask'])
    embedding_list = [embedding.unsqueeze(0) for embedding in embeddings]
    
    return embedding_list

# Constructing a viewpoint-graph using node embeddings.
def embedding_based_edge_connection(node_list: List[dict], config: dict) -> List[dict]:
    intra_gragh_deg = config["intra_graph_deg"]
    inter_gragh_deg = config["inter_graph_deg"]
    batch_size = config["batch_size"]  # Set batch size for processing nodes in smaller batches

    # Create string_to_index mapping for node_ids
    raw_node_ids = [node["node_id"] for node in node_list] 
    node_ids = [re.sub(r'\[\d+\]', '', node_id) for node_id in raw_node_ids]
    paper_id_set = list(set(node_ids))
    string_to_index = {s: i for i, s in enumerate(paper_id_set)}
    node_indices = torch.tensor([string_to_index[node_id] for node_id in node_ids])

    node_embs = torch.stack([torch.tensor(node["embedding"]) for node in node_list]).squeeze(1)
    n = len(node_embs)
    
    edge_set = set()
    edge_list = []
    
    def store_edges(topk_indices, start_idx, scores):
        for row_idx, row in enumerate(topk_indices):
            for elem in row:
                tuple_pair = (min(start_idx + row_idx, elem), max(start_idx + row_idx, elem))
                if tuple_pair not in edge_set:
                    edge_set.add(tuple_pair)
                    data = {
                        "node_id1": raw_node_ids[start_idx + row_idx],
                        "node_id2": raw_node_ids[elem],
                        "relation": "unknown",
                        "logical_connector": "unknown",
                        "weight": float(scores[row_idx, elem]),
                    }
                    edge_list.append(data)
                    
    if batch_size == -1:
        batch_size = n 
    for start_idx in tqdm(range(0, n, batch_size), desc="batches"):
        end_idx = min(start_idx + batch_size, n)

        # Extract the embeddings for the current batch
        batch_embs = node_embs[start_idx:end_idx]

        # Calculate pairwise similarities with the entire node set
        scores = torch.matmul(batch_embs, node_embs.T)  # Shape: [batch_size, n]

        # Determine intra- and inter-graph connections
        intra_gragh_mask = node_indices[start_idx:end_idx].unsqueeze(1) == node_indices.unsqueeze(0) # Shape: [batch_size, n]
        inter_gragh_mask = ~intra_gragh_mask
        # Fill diagonal for intra-graph (self connections)
        intra_gragh_mask.fill_diagonal_(0)

        # Apply masks to calculate the actual scores
        intra_gragh_scores = scores * intra_gragh_mask.float() 
        inter_gragh_scores = scores * inter_gragh_mask.float()
        
        # Extract top-k connections for intra-graph and inter-graph
        intra_topk_values, intra_topk_indices = torch.topk(intra_gragh_scores, intra_gragh_deg, dim=1)
        inter_topk_values, inter_topk_indices = torch.topk(inter_gragh_scores, inter_gragh_deg, dim=1)

        # Store intra-graph edges
        store_edges(intra_topk_indices, start_idx, intra_gragh_scores)

        # Store inter-graph edges
        store_edges(inter_topk_indices, start_idx, inter_gragh_scores)

    return edge_list

# Pipeline for constructing a viewpoint-graph using the embedding-based approach.
# After setting up the config.yaml file, run the following command:
# python -c "from Graph_Extraction import embedding_based_graph_construction; embedding_based_graph_construction()"
def embedding_based_graph_construction() -> Tuple[List[dict], List[dict], int]:
    with open("config.yaml", 'r', encoding='utf-8') as file:
        config = yaml.safe_load(file)
    
    dataset = load_dataset(config["dataset_path"])
    dataset = dataset[:20]
            
    tokenizer = AutoTokenizer.from_pretrained('facebook/contriever')
    encoder = AutoModel.from_pretrained('facebook/contriever')
    
    node_list = []
    token_usage_list = []
    for datum in tqdm(dataset, desc="Viewpoint Extraction"):
        paper_id = datum['paper_id']
        idea = datum['abstract']
        viewpoint_list, token_usage = viewpoint_extraction(idea, config)
        if token_usage: token_usage_list.append(token_usage)
        emb_list = get_node_embedding(viewpoint_list, tokenizer, encoder)
        
        idx = 0  
        for viewpoint, embedding in zip(viewpoint_list, emb_list):
            node_id = f"{paper_id}[{idx}]"
            node = {
                'viewpoint': viewpoint,
                'embedding': embedding.tolist(),  
                'node_id': node_id,
                'source': "extracted"
            }
            node_list.append(node)
            idx += 1
    
    save = config["save_node_list"]
    save_path = config["node_list_save_path"]
    save_path = os.path.join(save_path, 'node_list.jsonl')
    
    if save:
        with open(save_path, 'w', encoding='utf-8') as f:
            for node in node_list:
                f.write(json.dumps(node) + '\n')

    edge_list = embedding_based_edge_connection(node_list, config)
    # Write edge list to file
    save = config["save_edge_list"]
    if save:
        save_path = config["edge_list_save_path"]
        save_path = os.path.join(save_path, 'edge_list.jsonl')
        with open(save_path, 'w', encoding='utf-8') as f:
            for edge in edge_list:
                f.write(json.dumps(edge) + '\n')
    
    total_token_usage = sum(token_usage_list)
    return node_list , edge_list, total_token_usage 
        
